# Generated by Django 5.1.6 on 2025-02-09 05:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('population', models.IntegerField()),
                ('location_latitude', models.DecimalField(decimal_places=0, max_digits=9)),
                ('location_longitude', models.DecimalField(decimal_places=0, max_digits=9)),
            ],
            options={
                'db_table': 'city',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=14)),
                ('ext', models.CharField(blank=True, max_length=4, null=True)),
                ('is_fax', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'contact',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('email_id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'email',
                'ordering': ['value'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=250)),
                ('zip_code', models.CharField(max_length=5)),
                ('appartment', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'location',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('abbreviation', models.CharField(max_length=2)),
                ('capital', models.CharField(max_length=45)),
                ('incorporation_date', models.DateField(auto_now_add=True)),
                ('timezone', models.CharField(max_length=45)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Therapist',
            fields=[
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 2, 9, 5, 38, 50, 26606, tzinfo=datetime.timezone.utc))),
                ('created_by', models.CharField(max_length=25)),
                ('update_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=25, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=250)),
                ('user_id', models.IntegerField()),
                ('company_id', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'therapist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Therapist_Attribute',
            fields=[
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 2, 9, 5, 38, 50, 26606, tzinfo=datetime.timezone.utc))),
                ('created_by', models.CharField(max_length=25)),
                ('update_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=25, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=25)),
                ('value', models.CharField(max_length=250)),
                ('active', models.BooleanField(default=True)),
                ('visible', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'therapist_attribute',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Therapist_Contact',
            fields=[
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 2, 9, 5, 38, 50, 26606, tzinfo=datetime.timezone.utc))),
                ('created_by', models.CharField(max_length=25)),
                ('update_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=25, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('therapist_id', models.IntegerField()),
                ('contact_id', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('visible', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Therapist_Email',
            fields=[
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 2, 9, 5, 38, 50, 26606, tzinfo=datetime.timezone.utc))),
                ('created_by', models.CharField(max_length=25)),
                ('update_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=25, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('therapist_id', models.IntegerField()),
                ('email_id', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('visible', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Therapist_Invitation',
            fields=[
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 2, 9, 5, 38, 50, 26606, tzinfo=datetime.timezone.utc))),
                ('created_by', models.CharField(max_length=25)),
                ('update_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=25, null=True)),
                ('uuid', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('npi', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=25)),
                ('url', models.CharField(max_length=5000, null=True)),
                ('company_id', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='pending', max_length=10)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Therapist_Location',
            fields=[
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 2, 9, 5, 38, 50, 26606, tzinfo=datetime.timezone.utc))),
                ('created_by', models.CharField(max_length=25)),
                ('update_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=25, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('therapist_id', models.IntegerField()),
                ('location_id', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('visible', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
