# Generated by Django 5.1.6 on 2025-02-11 04:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Therapist_Signature',
            fields=[
                ('created_at', models.DateTimeField(default=datetime.datetime(2025, 2, 11, 4, 56, 55, 323692, tzinfo=datetime.timezone.utc))),
                ('created_by', models.CharField(max_length=25)),
                ('update_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=25, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('therapist_id', models.IntegerField()),
                ('signature', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('visible', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='therapist_contact',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 11, 4, 56, 55, 323692, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='therapist_email',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 11, 4, 56, 55, 323692, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='therapist_invitation',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 11, 4, 56, 55, 323692, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='therapist_location',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 11, 4, 56, 55, 323692, tzinfo=datetime.timezone.utc)),
        ),
    ]
