# Generated by Django 5.1.6 on 2025-05-08 22:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_therapist_signature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapist_contact',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 8, 22, 33, 37, 196461, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='therapist_email',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 8, 22, 33, 37, 196461, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='therapist_invitation',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 8, 22, 33, 37, 196461, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='therapist_invitation',
            name='npi',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='therapist_location',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 8, 22, 33, 37, 196461, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='therapist_signature',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 8, 22, 33, 37, 196461, tzinfo=datetime.timezone.utc)),
        ),
    ]
