# Generated by Django 5.1.6 on 2025-05-08 22:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_therapist_contact_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapist_contact',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 8, 22, 34, 34, 362819, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='therapist_email',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 8, 22, 34, 34, 362819, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='therapist_invitation',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 8, 22, 34, 34, 362819, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='therapist_invitation',
            name='email',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='therapist_location',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 8, 22, 34, 34, 362819, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='therapist_signature',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 8, 22, 34, 34, 362819, tzinfo=datetime.timezone.utc)),
        ),
    ]
